-- 코드를 입력하세요
SELECT YEAR(sales_date) YEAR,
    MONTH(sales_date) MONTH,
    GENDER,
    COUNT(DISTINCT ONLINE_SALE.USER_ID) USERS FROM ONLINE_SALE
LEFT JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC