-- 코드를 입력하세요
# SELECT FLAVOR FROM FIRST_HALF
#     WHERE TOTAL_ORDER > 3000
#     AND FLAVOR IN (
#         SELECT FLAVOR FROM ICECREAM_INFO
#             WHERE INGREDIENT_TYPE = 'fruit_based'
#     )
#     ORDER BY TOTAL_ORDER DESC
SELECT F.FLAVOR FROM FIRST_HALF AS F
    JOIN ICECREAM_INFO AS I
    ON F.FLAVOR = I.FLAVOR
    WHERE TOTAL_ORDER > 3000
    AND I.INGREDIENT_TYPE = 'fruit_based'
    ORDER BY F.TOTAL_ORDER DESC