-- 코드를 입력하세요
WITH RECURSIVE cte AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM cte WHERE HOUR < 23
)

SELECT cte.HOUR HOUR, COUNT(a.ANIMAL_ID) COUNT
FROM cte
    LEFT JOIN ANIMAL_OUTS a ON cte.HOUR = HOUR(a.DATETIME)
GROUP BY cte.HOUR
ORDER BY cte.HOUR