SELECT MEMBER_NAME, REVIEW_TEXT, LEFT(REVIEW_DATE, 10) AS REVIEW_DATE
FROM MEMBER_PROFILE
JOIN REST_REVIEW USING (MEMBER_ID)
WHERE MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
        SELECT COUNT(MEMBER_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
       LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT




    