-- 코드를 입력하세요
SELECT CAR_ID, IF(CAR_ID IN (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
      GROUP BY CAR_ID, START_DATE
      ORDER BY CAR_ID DESC
     ), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

# # -- 코드를 입력하세요
# SELECT CAR_ID, LEFT(START_DATE,10), LEFT(END_DATE,10), IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능' ) AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC

# SELECT CAR_ID, START_DATE, END_DATE
#      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#       WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
#       GROUP BY CAR_ID, START_DATE
#       ORDER BY CAR_ID DESC